### ISSUE TITLE
API Endpoint for getting all sections from courses

### ISSUE THREAD

**Issue by seveibar** [rcos/venue#274]
@jboulter11 should be consulted

**Comment by jboulter11** [comment]
I give you `courseId` or `SectionId` and my `sessionToken` if needed and you give me an `array of sectionEvents` for the desired course / section.

If we go with a `sectionId` instead of a `courseId` we need to figure out how to get that to me because I am currently (I think) storing a `courseId` for each course.

**Comment by kmcnellis** [comment]
@jboulter11 is this still an issue?

**Comment by jboulter11** [comment]
Nope!  I believe this is taken care of.  I have sectionId instead of
courseId now.

On August 12, 2016 at 11:44:38 AM, Kiana McNellis (notifications@github.com)
wrote:

@jboulter11 https://github.com/jboulter11 is this still an issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/rcos/venue/issues/274#issuecomment-239528101, or mute
the thread
