### ISSUE TITLE
CAS Auth redirects to localhost

### ISSUE THREAD

**Issue by ghost** [rcos/venue#369]
When using casauth on venue.rpi.edu and it looks like venue.cs.rpi.edu the redirect back to the venue server after sucessfull casuth incorrectly lists localhost:9000 not the DNS name of the server you started at.

http://localhost:9000/auth/cas?ticket=ST-146916-###############-cas-auth.server.rpi.edu #

**Comment by seveibar** [comment]
This was an issue when we were running development mode on the docker instance- because the docker instances now run production mode this isn't really an issue.

The exact cause of this is due to the override of `DOMAIN` in the `environment/development.js` file. That file is only read in development.

Thanks for reporting!!
